version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: testdb
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge